apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    type: backend
spec:
  template:
    metadata:
      name: backend-pod
      labels:
        type: backend
    spec:
      containers:
        - name: nginx
          image: nginx
  replicas: 3
  selector:
    matchLabels:
      type: backend
