apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  containers:
   - image: busybox
     name: busybox
     command: ["/bin/bash"]
     args: ["-c", 'i=0; while true; do echo "$i: $(date)"; i=$((i+1)); sleep 1; done']
