apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx2121
spec:
  containers:
  - image: nginx
    name: nginx
    envFrom: 
      - secretRef:
         name: my-secrets
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
